# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BASE_PATH: './src/playground'
  CADENCE_BASE_PATH: './src/cadence'
  DOCS_BASE_PATH: './docs'

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Build cadence for playground
        working-directory: ${{ env.CADENCE_BASE_PATH }}
        run: |
          pnpm i
          pnpm run generate:playground
      - name: Install playground
        working-directory: ${{ env.BASE_PATH }}
        run: pnpm i
      - name: Build
        working-directory: ${{ env.BASE_PATH }}
        run: APP_ENV=production  pnpm run build
      - name: Install docs dependencies
        working-directory: ${{ env.DOCS_BASE_PATH }}
        run: pnpm i
      - name: Build docs
        working-directory: ${{ env.DOCS_BASE_PATH }}
        run: |
          pnpm docs:build # or pnpm docs:build / yarn docs:build / bun run docs:build
          touch content/.vitepress/dist/.nojekyll
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Put all in a folder
        run: |
          mkdir ./pages
          cp -r ${{ env.DOCS_BASE_PATH }}/content/.vitepress/dist ./pages/
          cp -r ${{ env.BASE_PATH }}/dist ./pages/playground
          ls -la ./pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './pages/'

  # Deployment job
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
