name: Publish Package to npmjs
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.16.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Check lint
        working-directory: ./src/cadence
        run: pnpm run lint
      - name: Test
        working-directory: ./src/cadence
        run: pnpm run test
